name: CI Demo

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a basic Python script
      run: |
        echo "Running my first CI job"
        python --version
    
    - name: Run HelloWorld Python script
      run: python hello.py
